version: '3.4'

services:
  customers-api:
    ports:
      - "5010:5010"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5010

  orders-api:
    ports:
      - "5020:5020"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5020

  graphql-bff:
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - Urls__Customers=http://customers-api:5010/graphql
      - Urls__Orders=http://orders-api:5020/graphql 
    depends_on:
      - customers-api
      - orders-api

